### ISSUE TITLE
奶牛快传指定cookie之后并没有传到个人网盘中

### ISSUE THREAD

**Issue by Ivan-wang** [Mikubill/transfer#12]
是否我对于这个功能理解有误？我设置了remember-me字段，但是还是以临时文件上传的。

谢谢！

**Comment by Mikubill** [comment]
理论上应该是上传到对应账户的上传文件列表中，尚未开发传到个人网盘的功能。不过即使是传到文件上传列表中其有效期也是账号有效期，直接转存到网盘即可。

**Comment by Ivan-wang** [comment]
> 理论上应该是上传到对应账户的上传文件列表中，尚未开发传到个人网盘的功能。不过即使是传到文件上传列表中其有效期也是账号有效期，直接转存到网盘即可。

好的，了解了，谢谢！
