### ISSUE TITLE
通过lanzou api上传的文件好像无法删除

### ISSUE THREAD

**Issue by huanx9** [Mikubill/transfer#2]
有没有解决的办法 = =   
控制台好像找不到

**Comment by Mikubill** [comment]
可以试着把cookie的其他部分（像sessionID什么的）也放进去，如果懒的话直接复制console里Cookie 的那一块内容进去也行（未测试

--cookie='a=...;b=...;'


> *蓝奏云可以只使用phpdisk_info项作为cookie上传文件，但可能无法进行文件管理。如有需要可以将完整cookie放入flag中。

**Comment by Mikubill** [comment]
大概测试了一下，只要在原有cookie上再加一个`folder_id_c=-1`就能上传到根目录了，修改其值可以上传到不同的目录。（估计是和文件路径相关的信息
```
 ./transfer lzs --cookie="phpdisk_info=...; folder_id_c=-1" <file>
```

**Comment by huanx9** [comment]
可是我想删除我之前删除的部分阿 。想想办法

**Comment by Mikubill** [comment]
可以先在文件分享页面找到文件id，然后用api操作一下即可：
```
curl 'https://pc.woozooo.com/doupload.php' -H 'cookie: ...' --data 'task=6&file_id=<file-id>' 
```

**Comment by huanx9** [comment]
这个分享链文件ID 值得是 https://www.lanzous.com/XXXXXXXXX

XXX 部分吗，还是具体指的是 控制台里面会有一个单独的值

**Comment by huanx9** [comment]
我测试 curl+cookie 返回的是 `{"zt":0,"info":0,"text":0}` 说明登录是没有问题的

完整的写入 返回`{"zt":1,"info":"\u5df2\u5220\u9664","text":null}`  感觉是`文件没有找到`

**Comment by Mikubill** [comment]
文件id是纯数字，可以在页面源代码里找到：
![image](https://i.loli.net/2020/04/10/U8I6GVv1huZt3Og.png)
`?f=`后面接着一串数字的就是文件id
另： "\u5df2\u5220\u9664" -> "已删除"

**Comment by huanx9** [comment]
你一说 `举报链接` 源代码  我就理解了。  如果后续`transfer`可以通过分享链直接删就更好了。
如果没有这样的开发计划也没关系。。 
 感谢开发者 
 感谢开发者 
 感谢开发者 
重要的事情说三遍。 closed
