### ISSUE TITLE
GoFile上传报错

### ISSUE THREAD

**Issue by SUPERPCOW** [Mikubill/transfer#21]
`upload test.txt failed: PostUpload Error: parse body returns error: invalid character '<' looking for beginning of value`
![IMG_20201103_012431](https://user-images.githubusercontent.com/73215520/97899413-3c4ca580-1d74-11eb-8c2a-7433aa7426d2.jpg)

**Comment by Mikubill** [comment]
使用最新版本重试

**Comment by Mikubill** [comment]
问题已经在v0.4.8-beta2中修复。如仍有上述问题可以重新打开此issue
