### ISSUE TITLE
transfer wet 选项下载一直失败。

### ISSUE THREAD

**Issue by zhaojinzhou** [Mikubill/transfer#22]
failed DownloaderConfig with error: link is invaild or expired, onfile: deepspecch3.tar 
但是 浏览器下载就正常的。   
譬如说https://we.tl/t-DhL3mSBHNo

**Comment by Mikubill** [comment]
我这边没什么问题。可以使用beta版本的程序重新试试
https://github.com/Mikubill/transfer/releases/tag/v0.4.8-beta
```
fetching ticket.....ok
fetching download metadata...ok
file save to: /.../deepspecch3.tar
13.00 MiB / 1.90 GiB ...

```

**Comment by zhaojinzhou** [comment]
> 我这边没什么问题。可以使用beta版本的程序重新试试
> https://github.com/Mikubill/transfer/releases/tag/v0.4.8-beta
> 
> ```
> fetching ticket.....ok
> fetching download metadata...ok
> file save to: /.../deepspecch3.tar
> 13.00 MiB / 1.90 GiB ...
> ```


还是有问题~~~~~

----
[root@zhaojinzhou4 ~]# ./transfer wet   https://we.tl/t-DhL3mSBHNo
fetching ticket.......ok
fetching download metadata..failed DownloaderConfig with error: Get "https://download.wetransfer.com//eu2/9f908e834e9699c9710210773f0a6bee20201113061359/dcc1ad19a6e6847dfd6c36dad12b9ec0a9f867e4/deepspecch3.tar?cf=y&token=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MDU1MDA1MTgsInVuaXF1ZSI6IjlmOTA4ZTgzNGU5Njk5Yzk3MTAyMTA3NzNmMGE2YmVlMjAyMDExMTMwNjEzNTkiLCJmaWxlbmFtZSI6ImRlZXBzcGVjY2gzLnRhciIsIndheWJpbGxfdXJsIjoiaHR0cDovL3Byb2R1Y3Rpb24uYmFja2VuZC5zZXJ2aWNlLmV1LXdlc3QtMS53dDo5MjkyL3dheWJpbGwvdjEvc2Fya2FyLzNlYjc3ZWRmNzA3YjBiMzRjMjU2YTVlOGU4NjZhYTJjNDhmNDBjNTAxZDBjNDA5MzBhNjgyN2JiNjE0YjcyMThlMTZlZjFhOTFlMmFlNzM3OTZmMWNlIiwiZmluZ2VycHJpbnQiOiJkY2MxYWQxOWE2ZTY4NDdkZmQ2YzM2ZGFkMTJiOWVjMGE5Zjg2N2U0IiwiY2FsbGJhY2siOiJ7XCJmb3JtZGF0YVwiOntcImFjdGlvblwiOlwiaHR0cDovL3Byb2R1Y3Rpb24uZnJvbnRlbmQuc2VydmljZS5ldS13ZXN0LTEud3Q6MzAwMC93ZWJob29rcy9iYWNrZW5kXCJ9LFwiZm9ybVwiOntcInRyYW5zZmVyX2lkXCI6XCI5ZjkwOGU4MzRlOTY5OWM5NzEwMjEwNzczZjBhNmJlZTIwMjAxMTEzMDYxMzU5XCIsXCJkb3dubG9hZF9pZFwiOjEwNzQzMjY4ODk4fX0ifQ.TBN7JTy-B63pJZcFyd7HKsUn8BdAH5kCg3U02-y3oEc": read tcp 10.12.72.73:34244->99.84.238.120:443: read: connection reset by peer, onfile: deepspecch3.tar

**Comment by zhaojinzhou** [comment]
transfer_0.4.8-beta2_linux_amd64.tar.gz

**Comment by Mikubill** [comment]
connection reset by peer一般是是网络问题，计划以后加入重试功能
