### ISSUE TITLE
transfer gofile下载失败

### ISSUE THREAD

**Issue by malu2335** [Mikubill/transfer#23]
系统版本:windows10 专业版 20H2
软件版本：v0.4.8-beta
错误截图：
![屏幕截图 2020-11-18 202607](https://user-images.githubusercontent.com/45488790/99530710-a1430500-29dc-11eb-8583-9e736fad13f9.png)

**Comment by Mikubill** [comment]
我这边测试这个链接服务器返回的是500 Internal Server Error，可能是gofile出了点问题（
另外报错信息来看有点像是文件命名格式出错？试试`-o`选项指定文件名

**Comment by malu2335** [comment]
-o不能解决问题，需要-o然后把链接的https改成http才能进行下载 :( 
![image](https://user-images.githubusercontent.com/45488790/99535331-bcfdd980-29e3-11eb-88ef-d38dc83aa916.png)
