### ISSUE TITLE
没图床用了 有空的时候修复一下呗

### ISSUE THREAD

**Issue by huanx9** [Mikubill/transfer#25]
只有搜狗的可以用，其他的差不多都死透了。 
然而搜狗 还只有一天的有效期 。。  
大佬有空的时候修复一下呗

暂时用TG图床苟延残喘

**Comment by huanx9** [comment]
TG图床也没了。

**Comment by Mikubill** [comment]
已经对图床进行了检查和清理，现在应该可以使用了。
