### ISSUE TITLE
下载过程中如何解密？

### ISSUE THREAD

**Issue by AllenMeex** [Mikubill/transfer#28]
请问上传时使用了 --encrypt --encrypt-key=xxx 参数
下载时如何指定解密key?
试了下 --decrypt --decrypt-key=xxx  下载到的还是加密后的文件

**Comment by Mikubill** [comment]
用encrypt选项来解密即可

# decrypt stream when download
➜ ./transfer --encrypt --encrypt-key=123 https://....

**Comment by AllenMeex** [comment]
多谢，了解了，不好意思没仔细看文档。。
很好的项目
