### ISSUE TITLE
奶牛网盘上传完成后下载报错

### ISSUE THREAD

**Issue by gaoyunshu** [Mikubill/transfer#29]
奶牛网盘上传完成后可以打开下载页面但是点下载就报错了
浏览器显示：
{"error":"Document not found"}

**Comment by Mikubill** [comment]
与 https://github.com/Mikubill/cowtransfer-uploader/issues/30 一样的问题，稍后同步修复。（cowtransfer-uploader已经修复了这个问题，如果急着用可以先用那个）

**Comment by gaoyunshu** [comment]
好的，我想赞助这个工具，简直太方便了

**Comment by gaoyunshu** [comment]
另外网页版上传可满速    工具上传只有4分之一的速度   请问如何设置？或者有没有交流群方便讨论
