### ISSUE TITLE
wet上传失败

### ISSUE THREAD

**Issue by Slmie** [Mikubill/transfer#32]
Local: /home/Slmie/Havoc-OS/out/target/product/taimen/Havoc-OS-v4.3-20210330-taimen-Unofficial.zip
fetching upload tickets...getSendConfig(single mode) returns error: no csrf-token found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b2e9c]

goroutine 1 [running]:
transfer/apis/public/wetransfer.weTransfer.DoUpload(0x0, 0x0, 0xc000317180, 0x0, 0x1e, 0x0, 0x4, 0x0, 0x0, 0x0, ...)
        /home/runner/work/transfer/transfer/apis/public/wetransfer/upload.go:86 +0x19c
transfer/apis.upload(0x7ffe0d0f6454, 0x4f, 0x2d0171f7, 0x91e880, 0xc0001966e0, 0x1, 0x1, 0x63, 0x0)
        /home/runner/work/transfer/transfer/apis/upload.go:120 +0x317
transfer/apis.Upload(0xc00018b390, 0x1, 0x1, 0x91e880, 0xc0001966e0)
        /home/runner/work/transfer/transfer/apis/upload.go:67 +0x347
transfer/cmd.runner.func1(0xc000212f00, 0xc00018b380, 0x1, 0x1)
        /home/runner/work/transfer/transfer/cmd/controller.go:81 +0x17

**Comment by Mikubill** [comment]
已在v0.4.10修复 https://github.com/Mikubill/transfer/releases/tag/v0.4.10
