### ISSUE TITLE
linux amd64版本的 wet选项报  空指针错误无法使用

### ISSUE THREAD

**Issue by 89dexua** [Mikubill/transfer#34]
ransfer/main.go:6 +0x25
fetching ticket................................panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7b211b]

goroutine 1 [running]:
transfer/apis/public/wetransfer.weTransfer.download(0x0, 0x0, 0x0, 0x0, 0x1e, 0x0, 0x4, 0x0, 0x0, 0x0, ...)
        /home/runner/work/transfer/transfer/apis/public/wetransfer/download.go:50 +0xffb
transfer/apis/public/wetransfer.weTransfer.DoDownload(0x0, 0x0, 0x0, 0x0, 0x1e, 0x0, 0x4, 0x0, 0x0, 0x0, ...)
        /home/runner/work/transfer/transfer/apis/public/wetransfer/download.go:31 +0x9c
transfer/apis.Download(0x7ffc52a6f639, 0x1a, 0x91e9e0, 0xc0000c66e0)
        /home/runner/work/transfer/transfer/apis/download.go:18 +0xa2
transfer/cmd.handleRootTransfer(0xc0000c0050, 0x3, 0x3)
        /home/runner/work/transfer/transfer/cmd/root.go:93 +0x132
transfer/cmd.Execute()
        /home/runner/work/transfer/transfer/cmd/root.go:77 +0xf6
main.main()
        /home/runner/work/transfer/transfer/main.go:6 +0x25
fetching ticket................................panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7b211b]

**Comment by 89dexua** [comment]
mac版本的使用正常

**Comment by Mikubill** [comment]
我这边测试貌似没有问题，可以说下具体是什么情况下报错的吗
