### ISSUE TITLE
v0.4.10版本上传大文件10G以上无法下载并显示{"error":"Document not found"}

### ISSUE THREAD

**Issue by gaoyunshu** [Mikubill/transfer#35]
上传后可以到下载页面，点击下载则显示{"error":"Document not found"}

**Comment by Mikubill** [comment]
能否提供一下日志 （使用`--verbose`选项上传即可，记得删除敏感信息）

**Comment by Mikubill** [comment]
能否提供一下日志 （使用`--verbose`选项上传即可，记得删除敏感信息）

**Comment by gaoyunshu** [comment]
[日志.txt](https://github.com/Mikubill/transfer/files/6494134/default.txt)
太大了  cmd只能保存到后半部分

**Comment by gaoyunshu** [comment]
貌似我看出来了   分块太小  导致数量超过了10000

**Comment by Mikubill** [comment]
修了一个块大小的问题，使用beta版本重新上传试试

**Comment by gaoyunshu** [comment]
依然没有传输成功。，循环报错。

2021/05/19 14:40:26 part 10001 posting https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:26 endpoint: https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:26 returns: {"error":"partNum should be set from 1 to 10000"}
2021/05/19 14:40:26 part 10001 failed. error: partNum should be set from 1 to 10000
2021/05/19 14:40:26 part 10001 start uploading, size: 1666
2021/05/19 14:40:26 part 10001 posting https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:26 endpoint: https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
16.13 GiB / 16.13 GiB [------------------------------------------------------------------------------------------------------------------------>] 100.00% 0 B p/s ETA 0s2021/05/19 14:40:26 returns: {"error":"partNum should be set from 1 to 10000"}
2021/05/19 14:40:26 part 10001 failed. error: partNum should be set from 1 to 10000
2021/05/19 14:40:26 part 10001 start uploading, size: 1666
2021/05/19 14:40:26 part 10001 posting https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:26 endpoint: https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:26 returns: {"error":"partNum should be set from 1 to 10000"}
2021/05/19 14:40:26 part 10001 failed. error: partNum should be set from 1 to 10000
2021/05/19 14:40:26 part 10001 start uploading, size: 1666
2021/05/19 14:40:26 part 10001 posting https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:26 endpoint: https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:26 returns: {"error":"partNum should be set from 1 to 10000"}
2021/05/19 14:40:26 part 10001 failed. error: partNum should be set from 1 to 10000
2021/05/19 14:40:26 part 10001 start uploading, size: 1666
2021/05/19 14:40:26 part 10001 posting https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:26 endpoint: https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:26 returns: {"error":"partNum should be set from 1 to 10000"}
2021/05/19 14:40:26 part 10001 failed. error: partNum should be set from 1 to 10000
2021/05/19 14:40:26 part 10001 start uploading, size: 1666
2021/05/19 14:40:26 part 10001 posting https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:26 endpoint: https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:26 returns: {"error":"partNum should be set from 1 to 10000"}
2021/05/19 14:40:26 part 10001 failed. error: partNum should be set from 1 to 10000
2021/05/19 14:40:26 part 10001 start uploading, size: 1666
2021/05/19 14:40:26 part 10001 posting https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:26 endpoint: https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:27 returns: {"error":"partNum should be set from 1 to 10000"}
2021/05/19 14:40:27 part 10001 failed. error: partNum should be set from 1 to 10000
2021/05/19 14:40:27 part 10001 start uploading, size: 1666
2021/05/19 14:40:27 part 10001 posting https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001
2021/05/19 14:40:27 endpoint: https://upload-fog-cn-east-1.qiniup.com/buckets/cowtransfer-yz/objects/UU5fRk9HX2YxOTE5MWRiLWNkN2YtNDdjZC1iN2NkLTNkYTk5YjU1ZWFkZC82NjhkMzUzOC0zNjI3LTRjYmQtODgwNy1lOTk2OGFiNDViMmIv5Zyf5Zyw5rOVLTAwMjAyMTA1MTcwNDAzMTIubW92/uploads/60a4634c55cb39b10280806c/10001

**Comment by Mikubill** [comment]
~~修了一些手残~~。再试试（

**Comment by gaoyunshu** [comment]
可以用啦   感谢感谢

**Comment by hong0980** [comment]
Transfer has successfully downloaded.
fetching upload tickets..getSendConfig(single mode) returns error: no csrf-token found
Local: /home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/firmware/2021-0521-2222-openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b333c]

goroutine 1 [running]:
transfer/apis/public/wetransfer.weTransfer.DoUpload(0x0, 0x0, 0x0, 0x0, 0x1e, 0x1, 0x10, 0x0, 0x0, 0x0, ...)
	/home/runner/work/transfer/transfer/apis/public/wetransfer/upload.go:87 +0x19c
transfer/apis.upload(0xc00012c090, 0x90, 0x1a80304, 0x91e9e0, 0xc000080730, 0x1, 0x1, 0x98, 0x0)
	/home/runner/work/transfer/transfer/apis/upload.go:120 +0x317
transfer/apis.Upload(0xc000085510, 0x1, 0x1, 0x91e9e0, 0xc000080730)
	/home/runner/work/transfer/transfer/apis/upload.go:67 +0x347
transfer/cmd.runner.func1(0xc000116c80, 0xc0000809b0, 0x1, 0x5)
	/home/runner/work/transfer/transfer/cmd/controller.go:81 +0x176
github.com/spf13/cobra.(*Command).execute(0xc000116c80, 0xc000080960, 0x5, 0x5, 0xc000116c80, 0xc000080960)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xb5d0e0, 0x1, 0x1, 0xb5d860)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
transfer/cmd.Execute()
	/home/runner/work/transfer/transfer/cmd/root.go:75 +0x53
main.main()
	/home/runner/work/transfer/transfer/main.go:6 +0x25
出错啊
