### ISSUE TITLE
使用wetransfer 报错

### ISSUE THREAD

**Issue by MedyMa** [Mikubill/transfer#36]
![image](https://user-images.githubusercontent.com/75345465/119251539-9fe7d480-bbd9-11eb-964e-fe14aac672c5.png)

**Comment by 89dexua** [comment]
+1

**Comment by Mikubill** [comment]
wetransfer上传已修复(beta可用)，等待release发布即可。

**Comment by MedyMa** [comment]
5月31号发布的正式版也还是不能用，beta版没有问题

**Comment by Mikubill** [comment]
使用v0.4.11重试
