### ISSUE TITLE
最新版上传cowtransfer失败

### ISSUE THREAD

**Issue by liwenjie119** [Mikubill/transfer#38]
报错：
Transfer has successfully downloaded.
init Upload Error: Post "https://cowtransfer.com/transfer/preparesend": x509: certificate is valid for jy.ahzcxx.cn, not cowtransfer.com
Warning: init Upload Error: Post "https://cowtransfer.com/transfer/preparesend": x509: certificate is valid for jy.ahzcxx.cn, not cowtransfer.com

**Comment by Mikubill** [comment]
(dup https://github.com/Mikubill/cowtransfer-uploader/issues/34)

Cowtransfer在部分环境访问疑似出现解析问题，可以在`/etc/hosts`里指定一下服务器IP

可以选用以下IP地址
```
globalcdndynamic.qiniu.com.w.kunlungr.com. 55 IN A 49.7.22.216
globalcdndynamic.qiniu.com.w.kunlungr.com. 55 IN A 47.246.23.228
globalcdndynamic.qiniu.com.w.kunlungr.com. 60 IN A 47.89.66.205
globalcdndynamic.qiniu.com.w.kunlungr.com. 60 IN A 47.246.4.117
```

或者自己解析dns，选一个最快的
```bash
nslookup globalcdndynamic.qiniu.com.w.kunlungr.com
```

然后填到`/etc/hosts`里面就好
```
47.89.66.205 cowtransfer.com
```

**Comment by liwenjie119** [comment]
> (dup [Mikubill/cowtransfer-uploader#34](https://github.com/Mikubill/cowtransfer-uploader/issues/34))
> 
> Cowtransfer在部分环境访问疑似出现解析问题，可以在`/etc/hosts`里指定一下服务器IP
> 
> 可以选用以下IP地址
> 
> ```
> [globalcdndynamic.qiniu.com.w.kunlungr.com](http://globalcdndynamic.qiniu.com.w.kunlungr.com). 55 IN A [49.7.22.216](http://49.7.22.216)
> [globalcdndynamic.qiniu.com.w.kunlungr.com](http://globalcdndynamic.qiniu.com.w.kunlungr.com). 55 IN A [47.246.23.228](http://47.246.23.228)
> [globalcdndynamic.qiniu.com.w.kunlungr.com](http://globalcdndynamic.qiniu.com.w.kunlungr.com). 60 IN A [47.89.66.205](http://47.89.66.205)
> [globalcdndynamic.qiniu.com.w.kunlungr.com](http://globalcdndynamic.qiniu.com.w.kunlungr.com). 60 IN A [47.246.4.117](http://47.246.4.117)
> ```
> 
> 或者自己解析dns，选一个最快的
> 
> ```shell
> nslookup globalcdndynamic.qiniu.com.w.kunlungr.com
> ```
> 
> 然后填到`/etc/hosts`里面就好
> 
> ```
> [47.89.66.205](http://47.89.66.205) [cowtransfer.com](http://cowtransfer.com)
> ```

这个方法解决了我的本地上传的问题，但是github action内无法修改host，没办法。。。先用wet替代一下

**Comment by Mikubill** [comment]
GitHub Action改hosts可以参照这个试试

https://github.community/t/add-host-to-etc-hosts/17364


>
