### ISSUE TITLE
下载gofile的文件报错

### ISSUE THREAD

**Issue by azdttest** [Mikubill/transfer#40]
报错：
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
transfer/apis/public/gofile.goFile.download(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/transfer/transfer/apis/public/gofile/download.go:34 +0xc6b
transfer/apis/public/gofile.goFile.DoDownload(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/transfer/transfer/apis/public/gofile/download.go:25 +0xb4
transfer/apis.Download(0xc00001a360, 0x1a, 0xc7a7a0, 0xc00005b9a0)
        /home/runner/work/transfer/transfer/apis/download.go:18 +0xab
transfer/cmd.handleRootTransfer(0xc000004490, 0x1, 0x1)
        /home/runner/work/transfer/transfer/cmd/root.go:93 +0x134
transfer/cmd.Execute()
        /home/runner/work/transfer/transfer/cmd/root.go:77 +0xf7
main.main()
        /home/runner/work/transfer/transfer/main.go:6 +0x27

**Comment by Mikubill** [comment]
已修复。使用最新版本上传即可。
