### ISSUE TITLE
请问gof如何下载

### ISSUE THREAD

**Issue by gifyic** [Mikubill/transfer#42]
直接打开网址提示This file is not public，使用./transfer 下载报错fetching ticket...Download https://gofile.io/?c=svK3Yz Error: download failed on https://gofile.io/?c=svK3Yz, returns request https://api.gofile.io/getServer error: parse body returns error: invalid character '<' looking for beginning of，版本为0.4.12

**Comment by Mikubill** [comment]
该问题已在最新版本修复。使用最新版本上传即可。
