### ISSUE TITLE
linux armv6 版本 报 nil pointer dereference   【termux环境】

### ISSUE THREAD

**Issue by zhaojinzhou** [Mikubill/transfer#47]
:/data/data/com.termux/files/home # ./transfer Download Link: https://we.tl/t-EUv9Es6App
fetching ticket..panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c pc=0x325430]

goroutine 1 [running]:
transfer/apis/public/wetransfer.weTransfer.download(0x0, 0x0, 0x0, 0x0, 0x1e, 0x0, 0x4, 0x0, 0x0, 0x0, ...)
	/home/runner/work/transfer/transfer/apis/public/wetransfer/download.go:48 +0xc28
transfer/apis/public/wetransfer.weTransfer.DoDownload(0x0, 0x0, 0x0, 0x0, 0x1e, 0x0, 0x4, 0x0, 0x0, 0x0, ...)
	/home/runner/work/transfer/transfer/apis/public/wetransfer/download.go:29 +0x3c
transfer/apis.Download(0xbe9f87a8, 0x1a, 0x44ed08, 0x1894900)
	/home/runner/work/transfer/transfer/apis/download.go:18 +0x68
transfer/cmd.handleRootTransfer(0x189c108, 0x3, 0x3)
	/home/runner/work/transfer/transfer/cmd/root.go:93 +0xd0
transfer/cmd.Execute()
	/home/runner/work/transfer/transfer/cmd/root.go:77 +0xd8
main.main()
	/home/runner/work/transfer/transfer/main.go:6 +0x14

验证网络正常的。
2|:/data/data/com.termux/files/home # ping we.tl
PING we.tl (13.226.124.51) 56(84) bytes of data.
64 bytes from server-13-226-124-51.hkg62.r.cloudfront.net (13.226.124.51): icmp_seq=1 ttl=233 time=38.1 ms
64 bytes from server-13-226-124-51.hkg62.r.cloudfront.net (13.226.124.51): icmp_seq=2 ttl=233 time=38.4 ms
^C
--- we.tl ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 38.166/38.331/38.496/0.165 ms

**Comment by Mikubill** [comment]
`transfer/apis/public/wetransfer/download.go:48`←这里可能少了一个错误检查。
看起来好像是API问题，可以把日志输出一下吗（使用`-v`输出日志）

**Comment by Mikubill** [comment]
本地无法复现此问题。另外注意在使用下载功能时只需提供链接即可（不要添加多余的内容），如：

```
./transfer https://we.tl/t-EUv9Es6App
```
