### ISSUE TITLE
不能正常上传文件到奶牛快传

### ISSUE THREAD

**Issue by Aixzk** [Mikubill/transfer#48]
报错信息：
```
start upload failed: json: cannot unmarshal string into Go struct field prepareSendResp.error of type bool
```

**Comment by gaoyunshu** [comment]
同样的问题

**Comment by LIUBANGJIAN** [comment]
我也遇到相同的问题，作者还会修复更新吗？

**Comment by Mikubill** [comment]
奶牛快传目前禁止未登录用户上传。修复完成前可以暂时换用文叔叔等其他服务

**Comment by Aixzk** [comment]
> 奶牛快传目前禁止未登录用户上传。修复完成前可以暂时换用文叔叔等其他服务

已登录的PRO用户网页能上传，但使用 transfer 上传不了

**Comment by LIUBANGJIAN** [comment]
请问文叔叔是 wss吗

**Comment by Mikubill** [comment]
已修复。使用新版本上传即可（仅限登录用户

**Comment by Aixzk** [comment]
> 已修复。使用新版本上传即可（仅限登录用户

实测可用，感谢！

**Comment by KevinWang15** [comment]
我使用的是v0.4.17，仍然有这个问题

**Comment by pongfcnkl** [comment]
新版本又不行了
![QQ截图20231018221927](https://github.com/Mikubill/transfer/assets/24273319/8c08fdd4-9674-4330-afc5-668bebb3bb51)
