### ISSUE TITLE
request body too large，试了几家传输文件的商家都是这样的提示，是我参数设置不对吗?

### ISSUE THREAD

**Issue by liubangjain** [Mikubill/transfer#6]
-rw-r--r--  1 root root 85003472 Apr 15 07:55 PCQQ2020.exe
-rw-r--r--  1 root root      148 Aug 17  2015 .profile
-rw-r--r--  1 root root 84850808 Apr 17 23:31 qq.zip
drwxr-xr-x  3 root root     4096 Apr 17 04:50 test/
-rwxr-xr-x  1 root root  8163328 Apr 15 04:50 transfer*
-rw-------  1 root root     2601 Apr 17 04:36 .viminfo
-rw-r--r--  1 root root      281 Apr 14 21:27 virt-sysprep-firstboot.log
-rw-r--r--  1 root root      180 Apr 17 04:46 .wget-hsts
root@host:~# ./transfer -cow qq.zip 
Warning: backend is not set. Using default: filelink.backend - <filelink.io>
Run 'transfer --help' for usage.

Local: /root/qq.zip
50.89 MiB / 80.92 MiB [----------------------------->_________________] 62.89% 28.72 MiB p/s 2s
Download Link: http://i.filelink.io/http: request body too large

**Comment by Mikubill** [comment]
filelink更新了API，已经在新版本中修正了（下载新版本使用

另外cow的使用方法是

./transfer cow <file>

**Comment by liubangjain** [comment]
> 
> 
> filelink更新了API，已经在新版本中修正了（下载新版本使用
> 
> 另外cow的使用方法是
> 
> ./transfer cow （没有中划线）

[root@iZt4n1m4upe64d27nj9jbxZ ~]# curl -sL https://git.io/file-transfer | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   646  100   646    0     0   1194      0 --:--:-- --:--:-- --:--:--  1196
100 3182k  100 3182k    0     0   979k      0  0:00:03  0:00:03 --:--:-- 1290k

Transfer Downloded.

[root@iZt4n1m4upe64d27nj9jbxZ ~]# ./transfer cow PCQQ2020.exe 
Local: /root/PCQQ2020.exe
upload PCQQ2020.exe failed: start upload failed: unexpected end of JSON input
[root@iZt4n1m4upe64d27nj9jbxZ ~]#

**Comment by Mikubill** [comment]
cowtransfer貌似有API错误，正在检查

**Comment by Mikubill** [comment]
已修复该问题。可以重新测试一下

**Comment by liubangjain** [comment]
> 
> 
> 已修复该问题。可以重新测试一下

root@host:~# curl -sL https://git.io/file-transfer | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   646  100   646    0     0   4114      0 --:--:-- --:--:-- --:--:--  4114
100 3182k  100 3182k    0     0  3042k      0  0:00:01  0:00:01 --:--:-- 8151k

Transfer Downloded.

root@host:~# ls
cowtransfer.log  feeds.conf.default  PCQQ2020.exe  test      virt-sysprep-firstboot.log
custom-packages  lede                qq.zip        transfer
root@host:~# ./transfer  cow qq.zip 
Local: /root/qq.zip
80.92 MiB / 80.92 MiB [------------------------------------------>] 100.00% 2.69 KiB p/s ETA 0supload qq.zip failed: Do Upload Error: finishUpload returns error: Post "https://cowtransfer.com/transfer/uploaded": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

我试了一下，win版又正常。

**Comment by Mikubill** [comment]
看起来是timeout，多试几次就好了（可能是服务器端响应问题）

**Comment by liubangjain** [comment]
> 
> 看起来是timeout，多试几次就好了（可能是服务器端响应问题）

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
          
      - name: Upload firmware to wss
        run: |
          curl -sL https://git.io/file-transfer | sh 
          ./transfer wss ./bin/targets/

大佬，你好。我用GitHub的actions来编译openwrt的固件，然后想把固件上传到果内网盘，请问上传地址我是不是写错了？

**Comment by Mikubill** [comment]
> ...请问上传地址我是不是写错了？

（建议另开一个issue）看起来transfer的使用上没有什么问题。是出现了错误吗？

**Comment by Mikubill** [comment]
closed.
(issue问题已修复；如有问题可以重新打开)
