### ISSUE TITLE
cow上传文件名错误

### ISSUE THREAD

**Issue by liubangjain** [Mikubill/transfer#8]
执行一下命令
          curl -sL https://git.io/file-transfer | sh
          result=$(curl -s http://quan.suning.com/getSysTime.do)
          datetime=${result:13:10}_${result:24:8}
          zip -r lede_$datetime.zip ./bin/targets/
          ./transfer cow --no-progress ./*.zip
然后到奶牛网站下载，可以正常下载，但是等到的文件名是null没有后缀名，手动改.zip可以正常解压。

**Comment by garypang13** [comment]
我也一样,且文件夹中只上传了一个文件,

**Comment by Mikubill** [comment]
QwQ
已更新。使用新版本重试

**Comment by liubangjain** [comment]
测试正常
